### ISSUE TITLE
Windows specific bug

### ISSUE THREAD

**Issue by heeler** [AllenCellModeling/pylibczi#15]
the script below crashes on windows - osx & linux ok but windows 
```python
from aicspylibczi import CziFile
from pathlib import Path

pth = Path("~/Data/s_1_t_10_c_1_z_1.czi")

czi = CziFile(pth)
czi = CziFile(pth)
```

**Comment by cgohlke** [comment]
The crash is at 

https://github.com/AllenCellModeling/pylibczi/blob/81d12ef83689213ea55d84d25d4b10e0bc108e4c/_pylibczi/Reader.h#L90

**Comment by heeler** [comment]
Thank You for pointing me here. I'm trying to get my hands on a windows machine to test this on locally., Obviously I should be checking pointer values more carefully etc but there's a weirdness (to me at least) in how libCZI is handling their shared_ptr file object. I think I've figured out the problem but I'll have to test it. Big Thanks 🙌

**Comment by heeler** [comment]
So what's appears to be happening here is:
1) python creates and owns a BinaryIO object, which is associated with a file descriptor
2) C++ extension queries the BinaryIO for its file descriptor and uses it to open a file pointer
3) On windows, if the file pointer is closed the file descriptor is closed as well. This is what the docs say to do, use fclose not close. Since the file descriptor is owned by  Python closing the file pointer, which consequently closes the file descriptor. The file descriptor is owned by python and this results in a segfault.

I'm trying to figure out if there's a way to handle this on windows that neither causes a crash nor leaves the class with live file pointers.

**Comment by toloudis** [comment]
Just to recapitulate the issue here: python code was opening a file descriptor, and pylibczi's code was again opening and then closing it, which results in closing the file that was opened from within python.  The proper way to handle it is to use `dup` in the pylibczi side so that its open and close do not affect the file descriptor referenced by python.  @heeler Am I summarizing this correctly?   ( pull request #17  )

**Comment by heeler** [comment]
Yup! @toloudis that's in line with my thoughts. This bug is addressed in master and I hope to have the solution integrated into a wheel within a week.
